# Generated by Django 4.2.4 on 2023-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hexa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=10)),
                ('discription', models.CharField(max_length=500)),
            ],
        ),
    ]
