# Generated by Django 4.2.4 on 2023-08-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hexa',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
